CREATE TABLE "addresses" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "addresses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" bigint NOT NULL,
	"refresh_token_hash" varchar(64) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "consent_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "consent_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" varchar(100) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"required" boolean NOT NULL,
	"active" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "consent_items_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "jobs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "social_accounts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "social_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"provider" varchar(20) NOT NULL,
	"provider_user_id" varchar(255) NOT NULL,
	"email" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "social_accounts_provider_user_unique" UNIQUE("provider","provider_user_id"),
	CONSTRAINT "social_accounts_user_provider_unique" UNIQUE("user_id","provider")
);
--> statement-breakpoint
CREATE TABLE "user_consents" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_consents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"consent_item_id" bigint NOT NULL,
	"agreed" boolean NOT NULL,
	"agreed_at" timestamp with time zone,
	"withdrawn_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_consents_user_item_unique" UNIQUE("user_id","consent_item_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"job_id" bigint,
	"address_id" bigint,
	"nickname" varchar(255),
	"email" varchar(255),
	"gender" varchar(1),
	"age" integer,
	"role" varchar(32) DEFAULT 'PENDING' NOT NULL,
	"profile_image_key" varchar(512),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_nickname_unique" UNIQUE("nickname"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "auth_sessions" ADD CONSTRAINT "auth_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "social_accounts" ADD CONSTRAINT "social_accounts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_consents" ADD CONSTRAINT "user_consents_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_consents" ADD CONSTRAINT "user_consents_consent_item_id_consent_items_id_fk" FOREIGN KEY ("consent_item_id") REFERENCES "public"."consent_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_job_id_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_address_id_addresses_id_fk" FOREIGN KEY ("address_id") REFERENCES "public"."addresses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
INSERT INTO "consent_items" ("code", "name", "description", "required", "active") VALUES
  ('MARKETING', '마케팅 수신 동의', NULL, false, true),
  ('ADVERTISEMENT', '광고성 정보 수신 동의', NULL, false, true),
  ('NOTIFICATION', '알림 수신 동의', NULL, false, true);--> statement-breakpoint
INSERT INTO "addresses" ("name") VALUES
  ('서울특별시'),
  ('경기도'),
  ('세종특별자치시'),
  ('대전광역시'),
  ('광주광역시'),
  ('대구광역시'),
  ('부산광역시'),
  ('울산광역시'),
  ('경상남도'),
  ('경상북도'),
  ('전라남도'),
  ('전라북도'),
  ('충청남도'),
  ('충청북도'),
  ('강원도'),
  ('제주도'),
  ('독도/울릉도');--> statement-breakpoint
INSERT INTO "jobs" ("name") VALUES
  ('기획/전략'),
  ('법무,사무,총무'),
  ('인사/HR'),
  ('회계/세무'),
  ('마케팅/광고/MD'),
  ('개발/데이터'),
  ('디자인'),
  ('물류/무역'),
  ('운전/운송/배송'),
  ('영업'),
  ('고객상담/TM'),
  ('금융/보험'),
  ('식/음료'),
  ('고객서비스/리테일'),
  ('엔지니어링/설계'),
  ('제조/생산'),
  ('교육'),
  ('건축/시설'),
  ('의료/바이오'),
  ('미디어/문화'),
  ('스포츠'),
  ('공공복지'),
  ('자영업'),
  ('군인'),
  ('의료'),
  ('회계사'),
  ('법무사'),
  ('노무사'),
  ('세무사'),
  ('관세사'),
  ('교사'),
  ('디지털노마드'),
  ('영상제작자'),
  ('크리에이터');
