CREATE TABLE "jogak_executions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jogak_executions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"jogak_id" bigint NOT NULL,
	"scheduled_date" date NOT NULL,
	"status" varchar(16) NOT NULL,
	"jogak_title_snapshot" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "jogak_executions_jogak_scheduled_date_unique" UNIQUE("jogak_id","scheduled_date")
);
--> statement-breakpoint
CREATE TABLE "jogak_schedule_weekdays" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jogak_schedule_weekdays_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"schedule_id" bigint NOT NULL,
	"weekday" varchar(16) NOT NULL,
	CONSTRAINT "jogak_schedule_weekdays_schedule_weekday_unique" UNIQUE("schedule_id","weekday")
);
--> statement-breakpoint
CREATE TABLE "jogak_schedules" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jogak_schedules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"jogak_id" bigint NOT NULL,
	"schedule_type" varchar(16) NOT NULL,
	"effective_from" date NOT NULL,
	"effective_to" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "jogaks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jogaks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mogak_id" bigint NOT NULL,
	"title" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "modarats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "modarats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"title" varchar(100) NOT NULL,
	"color" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mogak_categories" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mogak_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" varchar(100) NOT NULL,
	"name" varchar(100) NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "mogak_categories_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "mogaks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mogaks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"modarat_id" bigint NOT NULL,
	"category_id" bigint,
	"custom_category_name" varchar(200),
	"title" varchar(100) NOT NULL,
	"color" varchar(100),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "jogak_executions" ADD CONSTRAINT "jogak_executions_jogak_id_jogaks_id_fk" FOREIGN KEY ("jogak_id") REFERENCES "public"."jogaks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jogak_schedule_weekdays" ADD CONSTRAINT "jogak_schedule_weekdays_schedule_id_jogak_schedules_id_fk" FOREIGN KEY ("schedule_id") REFERENCES "public"."jogak_schedules"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jogak_schedules" ADD CONSTRAINT "jogak_schedules_jogak_id_jogaks_id_fk" FOREIGN KEY ("jogak_id") REFERENCES "public"."jogaks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jogaks" ADD CONSTRAINT "jogaks_mogak_id_mogaks_id_fk" FOREIGN KEY ("mogak_id") REFERENCES "public"."mogaks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "modarats" ADD CONSTRAINT "modarats_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mogaks" ADD CONSTRAINT "mogaks_modarat_id_modarats_id_fk" FOREIGN KEY ("modarat_id") REFERENCES "public"."modarats"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mogaks" ADD CONSTRAINT "mogaks_category_id_mogak_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."mogak_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
INSERT INTO "mogak_categories" ("code", "name", "active") VALUES
  ('CERTIFICATION', '자격증', true),
  ('EXTERNAL_ACTIVITY', '대외활동', true),
  ('EXERCISE', '운동', true),
  ('INSIGHT', '인사이트', true),
  ('CONTEST', '공모전', true),
  ('JOB_STUDY', '직무공부', true),
  ('INDUSTRY_ANALYSIS', '산업분석', true),
  ('LANGUAGE', '어학', true),
  ('LECTURE', '강연,강의', true),
  ('PROJECT', '프로젝트', true),
  ('STUDY', '스터디', true),
  ('OTHER', '기타', true);
