-- Migration: 2026-08-17 v1
-- Applies after: legacy Spring schema is present
-- Purpose: repair the delete cascade through daily_jogak while preserving post rows.
CREATE TABLE IF NOT EXISTS jogak_schedules (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  jogak_id bigint NOT NULL REFERENCES jogak(jogak_id) ON DELETE CASCADE,
  schedule_type varchar(16) NOT NULL,
  effective_from date NOT NULL,
  effective_to date,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS jogak_schedule_weekdays (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  schedule_id bigint NOT NULL REFERENCES jogak_schedules(id) ON DELETE CASCADE,
  weekday varchar(16) NOT NULL,
  CONSTRAINT jogak_schedule_weekdays_schedule_weekday_unique UNIQUE (schedule_id, weekday)
);
CREATE OR REPLACE FUNCTION ensure_legacy_cascade_fk(child_table regclass, child_column text, parent_table regclass, parent_column text, constraint_name text) RETURNS void AS $$
DECLARE existing record;
BEGIN
  SELECT c.conname, c.confdeltype INTO existing FROM pg_constraint c
  JOIN pg_attribute child_attribute ON child_attribute.attrelid = c.conrelid AND child_attribute.attnum = c.conkey[1]
  JOIN pg_attribute parent_attribute ON parent_attribute.attrelid = c.confrelid AND parent_attribute.attnum = c.confkey[1]
  WHERE c.contype = 'f' AND c.conrelid = child_table AND c.confrelid = parent_table AND array_length(c.conkey, 1) = 1 AND child_attribute.attname = child_column AND parent_attribute.attname = parent_column LIMIT 1;
  IF existing.conname IS NOT NULL AND existing.confdeltype = 'c' THEN RETURN; END IF;
  IF existing.conname IS NOT NULL THEN EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', child_table, existing.conname); END IF;
  EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES %s (%I) ON DELETE CASCADE', child_table, constraint_name, child_column, parent_table, parent_column);
END;
$$ LANGUAGE plpgsql;
SELECT ensure_legacy_cascade_fk('mogak', 'modarat_id', 'modarat', 'modarat_id', 'mogak_modarat_cascade_fk');
SELECT ensure_legacy_cascade_fk('jogak', 'mogak_id', 'mogak', 'mogak_id', 'jogak_mogak_cascade_fk');
SELECT ensure_legacy_cascade_fk('daily_jogak', 'jogak_id', 'jogak', 'jogak_id', 'daily_jogak_jogak_cascade_fk');
DROP FUNCTION ensure_legacy_cascade_fk(regclass, text, regclass, text, text);
DO $$
DECLARE foreign_key record;
BEGIN
  FOR foreign_key IN SELECT constraint_name FROM information_schema.table_constraints WHERE table_schema = current_schema() AND table_name = 'post' AND constraint_type = 'FOREIGN KEY' AND constraint_name IN (SELECT constraint_name FROM information_schema.key_column_usage WHERE table_schema = current_schema() AND table_name = 'post' AND column_name = 'daily_jogak_id')
  LOOP EXECUTE format('ALTER TABLE post DROP CONSTRAINT %I', foreign_key.constraint_name); END LOOP;
END $$;
ALTER TABLE post_img ADD COLUMN IF NOT EXISTS position integer NOT NULL DEFAULT 0;
ALTER TABLE post_img ALTER COLUMN img_name SET DEFAULT '';
ALTER TABLE jogak ALTER COLUMN start_at SET DEFAULT CURRENT_DATE;
ALTER TABLE jogak ALTER COLUMN is_routine SET DEFAULT false;
ALTER TABLE daily_jogak ALTER COLUMN is_routine SET DEFAULT false;
ALTER TABLE post ALTER COLUMN comment_cnt SET DEFAULT 0;
ALTER TABLE post ALTER COLUMN like_cnt SET DEFAULT 0;
ALTER TABLE post ALTER COLUMN view_cnt SET DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS uq_daily_jogak_jogak_target ON daily_jogak (jogak_id, target_date);
CREATE UNIQUE INDEX IF NOT EXISTS uq_post_daily_jogak ON post (daily_jogak_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_follow_from_to ON follow (from_id, to_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_post_like_post_user ON post_like (post_id, user_id);
CREATE OR REPLACE VIEW mogak_categories AS SELECT mogak_category_id AS id, CASE name WHEN '자격증' THEN 'CERTIFICATION' WHEN '대외활동' THEN 'EXTERNAL_ACTIVITY' WHEN '운동' THEN 'EXERCISE' WHEN '인사이트' THEN 'INSIGHT' WHEN '공모전' THEN 'CONTEST' WHEN '직무공부' THEN 'JOB_STUDY' WHEN '산업분석' THEN 'INDUSTRY_ANALYSIS' WHEN '어학' THEN 'LANGUAGE' WHEN '강연,강의' THEN 'LECTURE' WHEN '프로젝트' THEN 'PROJECT' WHEN '스터디' THEN 'STUDY' ELSE 'OTHER' END AS code, name, true AS active, NULL::timestamp with time zone AS created_at, NULL::timestamp with time zone AS updated_at FROM mogak_category;
INSERT INTO jogak_schedules (jogak_id, schedule_type, effective_from, effective_to) SELECT j.jogak_id, CASE WHEN j.is_routine THEN 'WEEKLY' ELSE 'ONCE' END, COALESCE(j.start_at, CURRENT_DATE), CASE WHEN j.is_routine THEN j.end_at ELSE NULL END FROM jogak j WHERE NOT EXISTS (SELECT 1 FROM jogak_schedules s WHERE s.jogak_id = j.jogak_id);
INSERT INTO jogak_schedule_weekdays (schedule_id, weekday) SELECT s.id, CASE EXTRACT(DOW FROM s.effective_from) WHEN 0 THEN 'SUNDAY' WHEN 1 THEN 'MONDAY' WHEN 2 THEN 'TUESDAY' WHEN 3 THEN 'WEDNESDAY' WHEN 4 THEN 'THURSDAY' WHEN 5 THEN 'FRIDAY' ELSE 'SATURDAY' END FROM jogak_schedules s WHERE s.schedule_type = 'WEEKLY' AND NOT EXISTS (SELECT 1 FROM jogak_schedule_weekdays w WHERE w.schedule_id = s.id);
