/* global URL, console, process */

import 'dotenv/config';
import pg from 'pg';

function connectionStringFromEnvironment() {
  if (process.env.DATABASE_URL) return process.env.DATABASE_URL;
  const jdbcUrl = process.env.APP_DB_URL;
  if (!jdbcUrl) throw new Error('DATABASE_URL or APP_DB_URL is required');
  const url = new URL(jdbcUrl.startsWith('jdbc:') ? jdbcUrl.slice('jdbc:'.length) : jdbcUrl);
  if (process.env.APP_DB_USERNAME) url.username = process.env.APP_DB_USERNAME;
  if (process.env.APP_DB_PASSWORD) url.password = process.env.APP_DB_PASSWORD;
  return url.toString();
}

const ddl = `
CREATE TABLE IF NOT EXISTS jogak_schedules (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  jogak_id bigint NOT NULL REFERENCES jogak(jogak_id) ON DELETE CASCADE,
  schedule_type varchar(16) NOT NULL,
  effective_from date NOT NULL,
  effective_to date,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS jogak_schedule_weekdays (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  schedule_id bigint NOT NULL REFERENCES jogak_schedules(id) ON DELETE CASCADE,
  weekday varchar(16) NOT NULL,
  CONSTRAINT jogak_schedule_weekdays_schedule_weekday_unique UNIQUE (schedule_id, weekday)
);
ALTER TABLE post_img ADD COLUMN IF NOT EXISTS position integer NOT NULL DEFAULT 0;
ALTER TABLE post_img ALTER COLUMN img_name SET DEFAULT '';
ALTER TABLE jogak ALTER COLUMN start_at SET DEFAULT CURRENT_DATE;
ALTER TABLE jogak ALTER COLUMN is_routine SET DEFAULT false;
ALTER TABLE daily_jogak ALTER COLUMN is_routine SET DEFAULT false;
ALTER TABLE post ALTER COLUMN comment_cnt SET DEFAULT 0;
ALTER TABLE post ALTER COLUMN like_cnt SET DEFAULT 0;
ALTER TABLE post ALTER COLUMN view_cnt SET DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_daily_jogak_jogak_target ON daily_jogak (jogak_id, target_date);
CREATE UNIQUE INDEX IF NOT EXISTS uq_post_daily_jogak ON post (daily_jogak_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_follow_from_to ON follow (from_id, to_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_post_like_post_user ON post_like (post_id, user_id);

CREATE OR REPLACE VIEW mogak_categories AS
  SELECT mogak_category_id AS id,
    CASE name
      WHEN '자격증' THEN 'CERTIFICATION' WHEN '대외활동' THEN 'EXTERNAL_ACTIVITY'
      WHEN '운동' THEN 'EXERCISE' WHEN '인사이트' THEN 'INSIGHT'
      WHEN '공모전' THEN 'CONTEST' WHEN '직무공부' THEN 'JOB_STUDY'
      WHEN '산업분석' THEN 'INDUSTRY_ANALYSIS' WHEN '어학' THEN 'LANGUAGE'
      WHEN '강연,강의' THEN 'LECTURE' WHEN '프로젝트' THEN 'PROJECT'
      WHEN '스터디' THEN 'STUDY' ELSE 'OTHER'
    END AS code,
    name, true AS active, NULL::timestamp with time zone AS created_at, NULL::timestamp with time zone AS updated_at
  FROM mogak_category;
`;

const backfill = `
INSERT INTO jogak_schedules (jogak_id, schedule_type, effective_from, effective_to)
SELECT j.jogak_id,
  CASE WHEN j.is_routine THEN 'WEEKLY' ELSE 'ONCE' END,
  COALESCE(j.start_at, CURRENT_DATE),
  CASE WHEN j.is_routine THEN j.end_at ELSE NULL END
FROM jogak j
WHERE NOT EXISTS (SELECT 1 FROM jogak_schedules s WHERE s.jogak_id = j.jogak_id);

INSERT INTO jogak_schedule_weekdays (schedule_id, weekday)
SELECT s.id,
  CASE EXTRACT(DOW FROM s.effective_from)
    WHEN 0 THEN 'SUNDAY' WHEN 1 THEN 'MONDAY' WHEN 2 THEN 'TUESDAY'
    WHEN 3 THEN 'WEDNESDAY' WHEN 4 THEN 'THURSDAY' WHEN 5 THEN 'FRIDAY'
    ELSE 'SATURDAY'
  END
FROM jogak_schedules s
WHERE s.schedule_type = 'WEEKLY'
  AND NOT EXISTS (SELECT 1 FROM jogak_schedule_weekdays w WHERE w.schedule_id = s.id);
`;

const pool = new pg.Pool({ connectionString: connectionStringFromEnvironment() });
const client = await pool.connect();
try {
  await client.query('BEGIN');
  await client.query(ddl);
  await client.query(backfill);
  await client.query('COMMIT');
  console.log('Legacy schema compatibility migration completed.');
} catch (error) {
  await client.query('ROLLBACK');
  throw error;
} finally {
  client.release();
  await pool.end();
}
